services:
  isomap:
    build: .
    container_name: isomap-runner
    volumes:
      - ./data:/data
      - ./output:/results
    working_dir: /results
    command: ["/output/isomap", "/data/isomap.dat"]